# Site settings
title: White House Dollar Collector Game
description: A fun game where you collect dollars and avoid obstacles in the White House
baseurl: "/barron6" # the subpath of your site, e.g. /blog
url: "https://waffleninja100.github.io" # Replace with your GitHub Pages URL

# Build settings
markdown: kramdown
theme: minima # You can change this to another theme if you prefer

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  posts:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Sass settings
sass:
  style: compressed

# GitHub Pages settings
github: [metadata]